// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'category',
      label: 'GENERAL',
      items: ['intro', {
        type: 'link',
        href: 'https://github.com/clashperk/clashofclans.js/blob/master/CHANGELOG.md',
        label: 'ChangeLog'
      }],
      collapsed: false
    },
    {
      type: 'category',
      label: 'CLASSES',
      items: [{
        type: 'autogenerated',
        dirName: 'api/classes'
      }],
      collapsed: false
    },
    {
      type: 'category',
      label: 'INTERFACES',
      items: [{
        type: 'autogenerated',
        dirName: 'api/interfaces'
      }],
      collapsed: true
    },
    // { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = sidebars;
